### ISSUE TITLE
Default tracker set, but wrong attribution received

### ISSUE THREAD

**Issue by hearbeathorror** [adjust/android_sdk#244] opened 2016-11-29 08:56 UTC
Hi,

I am trying to track preinstalls using adjust, and i have a custom tracker created on the dashboard, however when the "session" is created during the first install, the response i receive does not return back to me the tracker name that should point at the new tracker token. 

That is, if i set default tracker value to "foo123", the tracker name and tracker token i get in the response points to Organic. 

Is there a way to get the correct tracker name in the attribution? Or I am missing something from my end? I have followed the same steps mentioned in the README here about preinstalls. 

The application also uses deeplinking too. And I dont know if this issue connects to issue #193 .

Please assist.

Thanks

**Comment by uerceg** [comment] 2016-11-29 09:05
Hi @hearbeathorror 

Lemme just ask couple of additional questions. Which SDK version are you using? While testing this particular scenario, are you clicking on some tracker URL which involves deep linking in this whole test case or are you pretty much making the "organic" scenario, but with setting the default tracker and later expecting it in attribution callback?

Cheers

**Comment by hearbeathorror** [comment] 2016-11-29 09:17
So the idea is to track the installs in a certain type of a device. I am just launching the app , and calling the onCreate with the config params set (that is default tracker set). I presume, the response should receive the tracker name and value that points to this default tracker that i am pointing to. Since its just the launch, there are no links clicked initially.

The piece of code:

        AdjustConfig config = new AdjustConfig(appClassInstanceHere, appToken, environment);
        config.setEventBufferingEnabled(false);
        config.setSendInBackground(true);
        config.setLogLevel(LogLevel.VERBOSE);
        config.setDefaultTracker("somevaluehere");
        config.setOnAttributionChangedListener(AdjustManager.INSTANCE);
        config.setOnEventTrackingSucceededListener(this);
        config.setOnEventTrackingFailedListener(this);
        config.setOnSessionTrackingSucceededListener(this);
        config.setOnSessionTrackingFailedListener(this);

         Adjust.onCreate(config);

I tried this with android-criteo 4.7.0 and also the latest one 4.10.4

Thanks

**Comment by uerceg** [comment] 2016-11-29 09:25
Thanks for the detailed info, we're on it. Will ping you as soon as we check this.

**Comment by hearbeathorror** [comment] 2016-11-29 09:36
Just to confirm, would you be reproducing the same scenario at your end? Or would this be released in the next release?

**Comment by uerceg** [comment] 2016-11-29 09:37
Hi @hearbeathorror 

I have just tested this flow and it works as expected.

Lemme ask you this question: `somevaluehere` which you are setting for your default tracker - is that some dummy value you're using for testing purposes or tracker token of `actual tracker` which you have created on your dashboard?

**Comment by hearbeathorror** [comment] 2016-11-29 09:40
It is a value of the actual tracker that is on the dashboard. @uerceg

**Comment by uerceg** [comment] 2016-11-29 09:43
Interesting.

Can you try first app install scenario by performing these steps:

1. Uninstall the app completely from your test device.
2. Forget your test device from our backend so that install can be tracked (more info on how to forget the device can be found in here with the forget URL: https://github.com/adjust/android_sdk#ts-session-failed)
3. Install the app which has this default tracker set and check the verbose logs after that, attribution callback output as well.

Give it a try and lemme know about the results.

**Comment by hearbeathorror** [comment] 2016-11-29 10:12
Sure. I will check the same and let you know. Do campaigns need to be set when creating a new tracker ?

**Comment by uerceg** [comment] 2016-11-29 10:14
I guess for real production stuff, your AM is the best person to be asked about these questions. 

For testing purposes, making just one test tracker in the dashboard which you will use for testing this default tracker use case is enough. Getting that tracker in attribution callback instead of the organic one is indicating that everything works as expected in this scenario.

**Comment by hearbeathorror** [comment] 2016-11-29 10:18
Ah.. So if i use the adid of the organic tracker, will that cause issues to the live builds out there?

**Comment by uerceg** [comment] 2016-11-29 10:20
I am not sure I understood this question, sorry for that. Can you maybe explain me a bit more what do you think when saying `use the adid of the organic tracker`?

For the record, organic tracker is the tracker token which is automatically created on the dashboard for you and all non-attributed installs are assigned to that tracker. On the other side `adid` is the identifier for each device which is generated by the adjust.

**Comment by hearbeathorror** [comment] 2016-11-29 10:26
I thought that the adid i was receiving in the response points to the "Organic" adjust tracker. But i somehow managed to forget the device using the android_id attribute. And i got the tracker_name associated with the tracker_token in the response. Does that mean it works ?

**Comment by uerceg** [comment] 2016-11-29 10:32
In the response from the backend, you can find pretty much 7 attribution properties which we're later reporting to you in the attribution callback as well: tracker token, tracker name, campaign, network, creative, adgroup, click label. Not all of these properties are set up, so some of them have no values, that's of course dependant on how user have set the campaign. But when testing with test tracker, you should at least see tracker token and tracker name, because when creating the tracker in the dashboard you're being asked to name it and once created, you get it's token.

In your case (to test whether setting the default tracker token works properly) thing to check is following: Check if tracker token which you get in your attribution callback is the same as the one which you have set in this line:

```java
config.setDefaultTracker("somevaluehere");
```

If these two token values match, that's it, your install is properly attributed to the tracker token which you have set as the default one. Of course, tracker name property in the attribution callback should be the same as the one you entered in the dashboard when creating the tracker which you used for this testing case.

**Comment by hearbeathorror** [comment] 2016-11-29 10:36
Perfect!.. Thanks alot for your help :).. Any reasons why i might have had to forget the device first ? Will this happen in real scenarios ?

**Comment by uerceg** [comment] 2016-11-29 10:49
Well, the thing is that once you have installed the app on your test device, for the first time when that happened, our backend tracked an install of that app on that device and assigned some attribution to it. In your case, probably organic one. As far as our backend is concerned, when it comes to your app on that test device, attribution will be organic unless it changes at some point. Change of attribution pretty much means that reattribution needs to happen (how to test this, again it's better to ask your AM).

So, at some point, you have decided to start using default tracker option and let's say you have uninstalled the app from your test device w/o forgetting it from our backend. You install the app, app starts with default tracker config set, session is being sent to our backend with `default_tracker` info, but our backend knows that your device already has this app installed since some time ago and that it's attribution is organic. Getting new info about this `default_tracker` in new session (if we assume that reattribution won't happen from it) will cause our backend just to ignore this info and say that organic is still the attribution for your device and your app on it. And this is why, when our SDK inside of your app asks for the attribution, backend is sending organic attribution as a response which you later see in the attribution callback.

Forgetting the device from our backend helps you to simulate scenario in which user installs your app for the first time ever and to check how are different flows happening in that scenario. Pre-defined tracker option is pretty much intended for this use case anyway -> for the users who are installing your app for the first time ever (probably outside of the Play Store, but some other store/source) and you would like to point them to some specific tracker which you made for that store/source instead of assigning all of those installs to organic tracker.

**Comment by hearbeathorror** [comment] 2016-11-29 10:57
I understood .. So can reattribution take place ever from code ? Is there a way to know that the tracker currently sent and the one it is attached to is different hence reattribution is required ?

**Comment by uerceg** [comment] 2016-11-29 11:16
Lemme explain reattribution a bit.

Reattribution is process in which attribution of your user changes for some reason. This change is not initialised from code of your app.

In the dashboard, there is a setting in which you can set something which is called reattribution window. This value represents time which, if elapsed, your user who was inactive in using your app for that time is a candidate to be reattributed, if reattribution is supposed to happen. And reattribution usually happens if your user was inactive in using your app for more than reattribution window value and then for some reason he clicked on some ad/banner/whatever where you're running some campaign for your app and after click on that link, app gets opened and user pretty much starts using your app again.

Dummy example is:

1. Your user installed your app from Play Store on his own, w/o clicks on any ads/banners/whatever. So, she/he is an organic user.
2. You have decided that reattribution window setting for your app should be, for example, 7 days. This means: If user doesn't use my app for 7 days or more, next time when he opens my app, I would like him to be considered for reattribution.
3. In the meantime, you're running some campaign for your app on (let's say Facebook). This user from above who didn't open your app for 7++ days uses Facebook and sees an ad for your app. He clicks that and app (which he already has installed on his device) gets opened.
4. In this moment, what our SDK does is, of course, sends new session to the backend and backend knows about the click on the URL which guided the user to send this session. Then backend checks whether reattribution window for this user elapsed and because (in our case) it is, attribution for this user `will be changed` to your campaign parameters on which link this user clicked and attribution for this user will no longer be organic, but will have parameters now from this campaign of yours.
5. Once this change on the backend occurred, backend will inform SDK about it and SDK will trigger your attribution callback which you have implemented in your app and inform you as well about this new attribution which your user now has.

**Comment by hearbeathorror** [comment] 2016-11-29 11:22
Oh okay. So that means , if a user has a preinstalled app with a certain token, then in that case, if the user does not use the app for some couple of days as per the settings, and now the user clicks on some campaign, in that case, his attributions will change, and it would no longer be part of a preinstall app correct?

**Comment by uerceg** [comment] 2016-11-29 11:28
Nope.

Let's you have set pre-installed tracker token for your user (let's say `abc123` tracker token). Your user downloads the app and installs it. Install which we track will be assigned to `abc123` tracker token in your dashboard. If your user at some alter point of time gets reattributed (let's say to tracker with token `def456`), that just means that his attribution changed, but install which was assigned to `abc123` won't disappear from there and be added to `def456`. Install of this user will always be tied to `abc123`.

**Comment by hearbeathorror** [comment] 2016-12-01 07:45
Hi @uerceg  - Thanks alot for the explanations. I passed them over to the Project Manager and i am sure they know what should be done. Incase i need help regarding setting the inactive period, please let me know where i should look into or may be some screenshot where i need to set it on the admin panel. 

Thanks once again

**Comment by uerceg** [comment] 2016-12-01 07:53
Hi @hearbeathorror 

No problemo. For those settings, you can go to your app in the dashboard and select `Attribution` and then `Reattribution Settings`. All settings you can find in there are explained as well.

Again, make sure that you fully understand what can be caused by changing these values and the best person to talk to in that case is your account manager from the adjust.

Glad that it all worked.

Cheers

**Closed by uerceg** 2016-12-01 07:53 UTC

**Comment by hearbeathorror** [comment] 2016-12-06 02:53
@uerceg - Hi !. I am sorry i had to bother you again, but i tried forgetting the device, and the issue i was talking about has come back again. Is there something really wrong in the way things are configured in the admin panel? Will you please let me know how to approach this ?

Thanks

**Comment by hearbeathorror** [comment] 2016-12-14 03:58
@uerceg - Hi!.. A small question for you . I saw the reattribution and attribution window and the values sets are 0 and 7 for attribution. However, when i was testing , if i dont use the application for a couple of days, it wud get associated with organic, until i forget the device manually. Is there a way i could ensure tht i dont hve to forget the device and it wud not get associated to organic ? Are the values provided correct ?

**Comment by uerceg** [comment] 2016-12-14 07:35
Hi @hearbeathorror

As far as those numer values are concerned, my advice to you is to check with your account manager what to set for them in case you are unsure about their meaning. It influences the number of reattributions of your users, so I guess if you are unsure about what to put in there, check with your AM from adjust.

I did not quite understand this sentence in which you are saying that you would be associated with organic in case that you don't use the app for couple of days. Can you explain me this a bit?

Thanks in advance.

**Comment by hearbeathorror** [comment] 2016-12-16 05:06
@uerceg : The idea is to keep a preinstalled app associated to a particular tracker value unless it is forcibly reattributed from the admin panel.

Unfortunately for testing in-house purposes i have to manually forget a device to make things work as they should. Even when the configuration is as under (in the attached images). We have the re-attribution settings set to 0, and the attribution set to 7. I wanted to understand how to set these values correctly to prevent forgetting a device manually (something i need to explain to my AM)..

<img width="430" alt="screen shot 2559-12-16 at 12 02 19 pm" src="https://cloud.githubusercontent.com/assets/5080780/21252244/e132ab9e-c387-11e6-8875-23507903aa98.png">
<img width="429" alt="screen shot 2559-12-16 at 12 02 34 pm" src="https://cloud.githubusercontent.com/assets/5080780/21252245/e13ab9a6-c387-11e6-8935-8821fb0e1482.png">

**Comment by hearbeathorror** [comment] 2016-12-21 06:41
@uerceg - i have one more question .. would this work with android-criteo 4.7.0 ?? The issue i had from the start or does the updated version also have an internal fix for this too ?

**Comment by uerceg** [comment] 2016-12-21 07:49
Hi @hearbeathorror 

Sorry for a bit delayed answer. Lemme try to answer to your both posts from above.

https://github.com/adjust/android_sdk/issues/244#issuecomment-267517938: First thing, I didn't quite understood what do you think when you say `forcibly reattributed from the admin panel`? Can you explain this a bit?

Setting `INACTIVE USER DEFINITION` to 0 should cause you user being constantly reattributed when ever he/she clicks maybe on a different tracker URL.

For example, let's imagine this scenario: Your user installed your app w/o click on any tracker URL before that, so it's an organic install and organic attribution. User closes the app and later that day he/she sees some add for your app (which has some tracker URL with tracker token `abc123` behind) and decides to click it. That will (if everything properly set), cause app to be opened and with this setting set to zero, user will get reattributed to your tracker with tracker token `abc123`. And so on. If later that day he/she sees some other add with another tracker behind it and clicks, will get reattributed to that, etc. That's why this setting is something you should consider with your product people, because with it being set to zero, you'll see bunch of reattributions of your users.

https://github.com/adjust/android_sdk/issues/244#issuecomment-268448968: I needed to read the whole thread once more to see what was the issue, but I am unsure that it's really an issue in the SDK, it's just that testing the whole flow was kinda mystery which I guess is now a bit clearer, right? Everything should work with our SDK versions with some of the plugins inside (Criteo, for example) as well. We always strongly advise to update to latest version (4.11.0 at this moment), but then again, you know the best how your development flow goes and when update to the latest adjust SDK version is feasible for you.

**Comment by hearbeathorror** [comment] 2016-12-26 04:34
@uerceg  - Hi!.. Forcibly reattributed means that, unless i forcibly assign a tracker to organic it should point to the adjust value it was associated with from the start. 

Setting INACTIVE USER DEFINITION to 0 should cause you user being constantly reattributed when ever he/she clicks maybe on a different tracker URL. -> For this setting, does that mean, if i click on any url or probably if i use the same app with other values, the attribution would change from the pre-install value to some other value ? What should the never value be ?

Thanks

**Comment by uerceg** [comment] 2016-12-26 08:45
Aah, you are talking about the default tracker.

So yes, if you choose to set default tracker option on the AdjustConfig object, instead of organic tracker, your installs will be associated to some default tracker that you have created in your dashboard. After that, reattribution flow happens pretty much as always, so regardless of where install was associated (organic or your default tracker). 

If 1000 of your users installs the app with the default tracker set to a tracker of your choice, you will see 1000 installs on the dashboard being assigned to your default tracker. But if some new tracker that you use for some capaign causes 100 out of these 1000 users to reattribute, you will still see 1000 as install number for default tracker and 100 as **reattributions** number on new tracker you use for your campaign.

**Comment by hearbeathorror** [comment] 2017-01-16 02:44
@uerceg  - Thanks for all your help.. I apologize for the delayed response.
