### ISSUE TITLE
ActivityState cast error

### ISSUE THREAD

**Issue by Geek4IT** [adjust/android_sdk#160] opened 2015-12-06 01:03 UTC
Hi, I am using the Adjust 4.0.8 version, and I collected this crash log in my dashboard, please help to check it:

java.lang.ClassCastException: com.adjust.sdk.ActivityState cannot be cast to java.util.List at com.adjust.sdk.PackageHandler.readPackageQueue(PackageHandler.java:202) at com.adjust.sdk.PackageHandler.initInternal(PackageHandler.java:165) at com.adjust.sdk.PackageHandler.access$0(PackageHandler.java:160) at com.adjust.sdk.PackageHandler$InternalHandler.handleMessage(PackageHandler.java:142) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:145) at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by uerceg** [comment] 2015-12-06 09:50
Hi @Geek4IT 

Thank you for your report. This was reported to us couple of times already. Is it possible for you to reproduce this crash? We were trying really hard in order to reproduce it, but never had any luck. If you can, it would be really helpful if you can write us down the steps needed to perform in order to reproduce it.

Anyway, fix which should prevent this thing happening was released in version https://github.com/adjust/android_sdk/releases/tag/v4.1.3 in https://github.com/adjust/android_sdk/pull/144.

**Comment by Geek4IT** [comment] 2015-12-07 06:53
It is hard for us to reproduce too, we just saw the crash log from the dashboard . We have more than 100 million users globally, and it crashes more than 10, 000 times already. If we plan to upgrade the Adjust SDK, which version is the most table one? The stability of the third-party SDK is very important for us. Thank you.

**Comment by uerceg** [comment] 2015-12-07 08:55
Of course. Last version available should always be the good choice, so feel free to chose that one once upgrading (currently https://github.com/adjust/android_sdk/releases/tag/v4.1.5).

In the meantime, we'll keep trying to reproduce this error, because it was reported sporadically and no one was able to reproduce it again. If you come up with some scenario which recreates it, it would be great if you can share it with us.

**Comment by nonelse** [comment] 2015-12-07 09:57
The error implies that one of the files is written as the other or that one of the files is read as the other.
The problem is that we can’t find a case where that is possible.
But @ugi is right, we've catched that exception in one of our updates and it should be able to recover to a something stable with that.

**Comment by uerceg** [comment] 2015-12-22 12:02
Okay, we have changed the way we're handling this. I think that you shouldn't face this error anymore. Feel free to reopen the issue if you still see it after this update. Thank you for your feedback once more.

Fix commit: https://github.com/adjust/android_sdk/commit/8d0b1dcf88b5100d04210c5fa674f50fff8c36d4
Pull request: https://github.com/adjust/android_sdk/pull/162
SDK release: https://github.com/adjust/android_sdk/releases/tag/v4.2.0

**Closed by uerceg** 2015-12-22 12:02 UTC
