### ISSUE TITLE
Crash on the Sdk

### ISSUE THREAD

**Issue by JosepLC** [adjust/android_sdk#203] opened 2016-07-25 16:24 UTC
Hi, yesterday I saw a crash on the google play developer console with the Adjust sdk.

We use the most recent version (4.7.0).

`java.lang.RuntimeException: 03
at xmoszwkq.eOqlqwPW.chaVJs4S(eOqlqwPW.java:26)
at xmoszwkq.unG7GkHE.yuARBFsW(Native Method)
at xmoszwkq.unG7GkHE.uBqVkHvi(unG7GkHE.java:109)
at xmoszwkq.unG7GkHE.A81KWsPh(unG7GkHE.java:82)
at xmoszwkq.unG7GkHE.l__KPNPR(unG7GkHE.java:36)
at com.adjust.sdk.AdjustReferrerReceiver.<clinit>(AdjustReferrerReceiver.java)
at java.lang.Class.newInstance(Native Method)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:3611)
at android.app.ActivityThread.access$2000(ActivityThread.java:222)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1877)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7229)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

Thanks in advance.

**Comment by uerceg** [comment] 2016-07-25 16:26
Hi @JosepLC 

Are you using only our broadcast receiver for `INSTALL_REFERRER` intent or do you have your own?

**Comment by JosepLC** [comment] 2016-07-25 16:29
hi @uerceg 

we are using your broadcast receiver, as it says in the Basic Installation Guide.

**Comment by uerceg** [comment] 2016-07-25 16:32
Is this something you can maybe reproduce white testing in sandbox? What was the frequency of this crash being reported in production? Is it widely spread or just randomly reported on couple of devices?

**Comment by JosepLC** [comment] 2016-07-25 16:34
It happened twice the same day on the production app, and we can not reproduce it.

**Comment by uerceg** [comment] 2016-07-25 16:54
Thank you for your report, we will take a look at this and get back to you as soon as we find something out.

**Comment by uerceg** [comment] 2016-07-25 16:59
@JosepLC 

Do you have information what is the Android version of the devices on which this crash happened? Is your app pure native Android app or written with some non native framework (Unity, Cordova, etc)?

**Comment by JosepLC** [comment] 2016-07-26 07:04
I was a native Android version, without any non native framework.

**Comment by nonelse** [comment] 2016-07-26 09:06
The error seems to occur during the initialisation of the [AdjustReferrerReceiver](https://github.com/adjust/android_sdk/blob/master/Adjust/adjust/src/main/java/com/adjust/sdk/AdjustReferrerReceiver.java) class. So even before [onReceive](https://github.com/adjust/android_sdk/blob/master/Adjust/adjust/src/main/java/com/adjust/sdk/AdjustReferrerReceiver.java#L19) is called.
Since it's the system that actually calls this code, it's not something we can capture and log the error.
The [documentation](https://developer.android.com/reference/android/content/BroadcastReceiver.html) doesn't go into details of the how a BroadcastReceiver is triggered besides that `Intent broadcast mechanism here is completely separate from Intents that are used to start Activities`.
I know that you already said that you've followed the the Basic installation guide, but can you check if `new AdjustReferrerReceiver()` is called anywhere on your code?
If not that, my guess is that the issue, comes from another part of the code and it comes crashing down on that initialisation.

**Comment by JosepLC** [comment] 2016-07-26 09:10
we look for "AdjustReferrerReceiver" and we are only using in the manifest, no "new AdjustReferrerReceiver()" in the java code.

**Comment by Obaied** [comment] 2016-11-08 14:50
Hey @JosepLC 
Was the issue resolved in our latest SDKs? If so, please let us know.

Cheers :)

**Comment by Obaied** [comment] 2017-02-09 13:43
I'll close the issue for now. Please feel free to reopen it if necessary

**Closed by Obaied** 2017-02-09 13:43 UTC
