### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by adilahsoft0611** [adjust/android_sdk#123] opened 2015-05-25 02:07 UTC
crashlytics report bug:
```
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
       at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1553)
       at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:306)
       at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleWithFixedDelay(ScheduledThreadPoolExecutor.java:567)
       at java.util.concurrent.Executors$DelegatedScheduledExecutorService.scheduleWithFixedDelay(Executors.java:653)
       at com.adjust.sdk.ActivityHandler.startTimer(ActivityHandler.java:687)
       at com.adjust.sdk.ActivityHandler.startInternal(ActivityHandler.java:392)
       at com.adjust.sdk.ActivityHandler.access$300(ActivityHandler.java:36)
       at com.adjust.sdk.ActivityHandler$SessionHandler.handleMessage(ActivityHandler.java:312)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```
what can i do to fix it?

**Comment by uerceg** [comment] 2015-05-25 08:17
Hi @adilahsoft0611 and thank you for your report.

Can you tell us how did you manage to trigger this exception and is it reproducible?

**Comment by adilahsoft0611** [comment] 2015-05-25 09:06
i can't. i get report from crashlytics.

**Comment by uerceg** [comment] 2015-05-25 10:30
And did it happen just once or did you see it more than once?

**Comment by adilahsoft0611** [comment] 2015-05-25 10:33
twice.

i attached the crashlytics screenshoots.

**Comment by adilahsoft0611** [comment] 2015-05-26 01:08
ups sorry, wrong attachment. i attach again.

**Comment by uerceg** [comment] 2015-05-26 08:52
Which SDK version are you using in your app? Can you please send us screenshots on support@adjust.com ?

**Comment by adilahsoft0611** [comment] 2015-05-27 01:48
i'm using adjust-android-4.0.2.jar

**Comment by nonelse** [comment] 2015-05-27 08:23
Although we cannot reproduce it, a possible culprit might be the creation of a [ScheduledExecutor](https://github.com/adjust/android_sdk/blob/v4.0.2/Adjust/adjust/src/main/java/com/adjust/sdk/ActivityHandler.java#L686) every time a timer is created, which is possibly every time there is a subsession.
I was already finishing a change on the way we use the [timer](https://github.com/adjust/android_sdk/commit/b15b878f10f9e634b5829452dd226b532ac378a8), so probably this issue might be fixed with this new release.
I'll update here when it's out.

Thanks!

**Comment by nonelse** [comment] 2015-06-10 13:17
The new version [v4.0.8](https://github.com/adjust/android_sdk/releases/tag/v4.0.8) changed the way the timer is used. 
Can you see if it fixed the problem?

**Comment by adilahsoft0611** [comment] 2015-06-11 02:38
to see it's fix or not the problem, i must republish app.

i plan to publish new version app on next week. off course, i will include
to update adjust lib to v4.0.8 on that version.

**Comment by adilahsoft0611** [comment] 2015-07-01 01:41
Again, i got error on crashlytics bug report.

Capture attached



Toni Kustiana

elevenia android dev

**Comment by nonelse** [comment] 2015-07-01 09:22
hi @adilahsoft0611, it seems that there wasn't anything attached to your comment. Was it the same error?
You can contact us directly at support@adjust.com and ask to redirect to the SDK team

**Comment by uerceg** [comment] 2016-03-03 11:11
Hi @adilahsoft0611 

Are you maybe facing this issue with newest android SDK version?

**Comment by uerceg** [comment] 2016-04-18 06:46
Please, reopen if you are still facing this version with latest SDK update.

**Closed by uerceg** 2016-04-18 06:46 UTC

**Comment by andreykadatsky** [comment] 2017-03-17 17:09
Hi guys, I have 88 logs in crashlytics with the same issue (Adjust 4.11.1) for last week. 
It happens when I call `Adjust.onPause();` in the Activity#onPause().
Could you suggest something?

```
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:1063)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1553)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:306)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:503)
	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:602)
	at com.adjust.sdk.Q.a(CustomScheduledExecutor.java:60)
```

**Comment by Obaied** [comment] 2017-03-17 17:14
Hey Andrey

Can you send us the SDK initialization codes? Just wanna see how this
OutOfMemory Exception occured.


On Mar 17, 2017 6:09 PM, "Andrey" <notifications@github.com> wrote:

Hi guys, I have 88 logs in crashlytics with the same issue (Adjust 4.11.1)
for last week.
It happens when I call Adjust.onPause(); in the Activity#onPause().
Could you suggest something?

java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:1063)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1553)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:306)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:503)
	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:602)
	at com.adjust.sdk.Q.a(CustomScheduledExecutor.java:60)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/adjust/android_sdk/issues/123#issuecomment-287414613>,
or mute the thread

**Comment by rimmer** [comment] 2017-03-18 12:54
Hey, @Obaied, I'm working with @andreykadatsky.
Will try to clarify. 

```java
// this is called on Application#onCreate
private static void initAdjust(Application application) {
        final String appToken = application.getString(R.string.adjust_key);

        final String environment = AdjustConfig.ENVIRONMENT_PRODUCTION;
        AdjustConfig config = new AdjustConfig(application, appToken, environment);

        Adjust.onCreate(config);
}

// This is called on Activity#onPause
public static void onActivityPause(Activity activity) {
    Adjust.onPause();
}

// This is called on Activity#onResume
public static void onActivityResume(Activity activity) {
    Adjust.onResume();
}
```

**Comment by uerceg** [comment] 2017-03-21 16:40
Hi @andreykadatsky and @rimmer 

We're investigating this on our side, still unable to reproduce it. In the meanwhile, out of curiosity - is crashlytics showing any other Out Of Memory exceptions in your app which stack trace does not include Adjust SDK?

Cheers

**Comment by uerceg** [comment] 2017-03-21 16:44
Also, is there some certain API level on the devices on which this issue is being seen or is the API level distribution random?

**Comment by andreykadatsky** [comment] 2017-03-21 17:17
@uerceg Thanks for reply. Yes there was another OutOfMemoryError, but it was connected with  Timer memory leak on Samsung devices, and we already fixed it.

About devices & api versions of issue connected with Adjust SDK:
Top devices: XIAOMI REDMI 3, ONEPLUS A3003, SAMSUNG SM-A9000, SAMSUNG BQ3, lenovo k50-t3s.
OS version: 5.0.2 - 7.1.1 (mostly 5.1)

**Comment by andreykadatsky** [comment] 2017-04-04 13:02
@uerceg @Obaied any update?

**Comment by Obaied** [comment] 2017-04-04 13:23
Hey @andrey. We've ran an extensive memory usage check on the API level you specified. Our RAM footprint is minimal. 

Adjust.onPause() basically just writes the state of the SDK to an external file for later retrieval. It's not a huge data dump.

Can you tell us how are you reproducing the issue? That info would help us.

**Comment by humanooab** [comment] 2018-03-20 10:46
Hey guys,
I know it was a year ago, but I also have the same OutOfMemory, as @andreykadatsky in my app. The issues I can see on crashlytics with the exactly the same crashlog

**Comment by josempans** [comment] 2018-03-23 18:10
We are having some crashes as well (also the log is from crashlytics):
`Fatal Exception: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:731)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
       at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1582)
       at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:313)
       at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
       at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:635)
       at com.adjust.sdk.CustomScheduledExecutor.submit(CustomScheduledExecutor.java:60)
       at com.adjust.sdk.ActivityHandler.onPause(ActivityHandler.java:295)
       at com.adjust.sdk.AdjustInstance.onPause(AdjustInstance.java:94)
       at com.adjust.sdk.Adjust.onPause(Adjust.java:51)`

**Comment by uerceg** [comment] 2018-03-23 18:11
Thanks guys for reporting, we will investigate the issue and keep you posted in here.

**Comment by uerceg** [comment] 2018-03-23 19:11
@josempans For which SDK version did you see this crash happening?

**Comment by uerceg** [comment] 2018-03-23 19:13
Also @josempans and @humanooab would it be possible to give latest SDK version a try and let us know if you're still facing these crashes?

**Comment by uerceg** [comment] 2018-03-23 19:18
Also, did you make sure that during the analysis of your apps there aren't any reported memory leaks happening?

**Comment by josempans** [comment] 2018-05-28 20:07
@uerceg Sorry the delay, :P. By that time I've updated to 4.12.4, but we have some crashes with the same log. Now I'm updating to 4.13.0

`Fatal Exception: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:733)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:970)
       at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1611)
       at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:342)
       at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
       at com.adjust.sdk.CustomScheduledExecutor.schedule(CustomScheduledExecutor.java:64)
       at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:664)
       at com.adjust.sdk.CustomScheduledExecutor.submit(CustomScheduledExecutor.java:54)
       at com.adjust.sdk.ActivityHandler.onPause(ActivityHandler.java:312)
       at com.adjust.sdk.AdjustInstance.onPause(AdjustInstance.java:106)
       at com.adjust.sdk.Adjust.onPause(Adjust.java:51)
       at .GameApplication$AdjustLifecycleCallbacks.onActivityPaused(GameApplication.java:240)`
