### ISSUE TITLE
invocationTargetException 

### ISSUE THREAD

**Issue by minichip17** [adjust/android_sdk#389] opened 2019-09-16 08:02 UTC
Does anyone have idea about this ?? 

E/Adjust: closeReferrerClient error (null) thrown by (java.lang.reflect.InvocationTargetException)

Here my code ... 

String environment = AdjustConfig.ENVIRONMENT_SANDBOX;
        AdjustConfig config = new AdjustConfig(this, BuildConfig.AdjustMixPanelToken, environment);
        Adjust.onCreate(config);
        config.setOnAttributionChangedListener(new OnAttributionChangedListener() {
            @Override
            public void onAttributionChanged(AdjustAttribution attribution) {
                MixpanelAPI mixpanel = MixpanelAPI.getInstance(getApplicationContext(), "lkrdh5h6j5zk");

                // The adjust properties will be sent
                // with all future track calls.
                JSONObject props = new JSONObject();

                insertJsonProperty(props, "[Adjust]Network", attribution.network);
                insertJsonProperty(props, "[Adjust]Creative", attribution.creative);

                if (props.length() > 0)
                    mixpanel.registerSuperProperties(props);
            }

            private void insertJsonProperty(JSONObject props, String name, String value) {
                try {
                    if (value != null) {
                        props.put(name, value);
                    }
                } catch(JSONException e) { }
            }
        });

        Adjust.onCreate(config);
        registerActivityLifecycleCallbacks(new AdjustLifecycleCallbacks());

**Comment by uerceg** [comment] 2019-09-16 08:31
Hi @minichip17 

Adjust SDK upon launch is trying to read referrer information from Google Referrer API if it's present in the app. This message points out that SDK didn't manage to read that information. It's because you didn't add `installreferrer` library to your app like described in [this chapter](https://github.com/adjust/android_sdk#qs-gpr-api). Of course, if you're distributing your app outside of Play Store and are not interested in collecting Google Advertising Id, then you don't need to add this dependency to your app and error message will be there, but it's causing no harm at all, so you can feel free to ignore it.

In case you have any further questions, feel free to ping.

Cheers

**Comment by minichip17** [comment] 2019-09-16 09:00
Hey uerceg ,

Thanks for response , i have added

 implementation 'com.adjust.sdk:adjust-android:4.16.0'
   implementation 'com.android.installreferrer:installreferrer:1.0'
in my App gradle . 

Thats the exact issue which i am facing :
The source of the marketing is missing in all cases of Android installations meaning that XYZApp are unable to see which marketing is driving app installs.

All data is coming through as 'undefined' which means Adjust does not know where it has come from.

**Comment by minichip17** [comment] 2019-09-16 13:15
Hey @uerceg  , 

Waiting for the reply .

**Comment by uerceg** [comment] 2019-09-16 19:02
Hi @minichip17 

This is unfortunately something which I don't think we can efficiently help you with in here. This is more of a question for our account management / integration team since not attributing installs to proper source can be caused by many different things (are trackers for the app generated in the dashboard, are they being used properly, are campaigns running, etc) which they can help you debug and discover what is the issue. In SDK repo issues we are mostly focused on helping out with issues related to SDK and integration of it.

Feel free to contact your dedicated account manager with detailed description of the issue your client is facing and in case you don't have one, feel free to send an email to support@adjust.com.

I will close this issue and feel free to reopen it in case you encounter further issues related to SDK itself.

Cheers.

**Closed by uerceg** 2019-09-16 19:02 UTC
