### ISSUE TITLE
NullPointerException sendClickPackage

### ISSUE THREAD

**Issue by fleficher** [adjust/android_sdk#132] opened 2015-06-25 22:00 UTC
Hi,

Since 4.0.6 were are experiencing crashs with Adjust. Here's the stacktrace from crashlytics : 
<pre><code>
java.lang.NullPointerException
       at com.adjust.sdk.PackageHandler.sendClickPackage(PackageHandler.java:121)
       at com.adjust.sdk.ActivityHandler.sendReferrerInternal(ActivityHandler.java:529)
       at com.adjust.sdk.ActivityHandler.access$800(ActivityHandler.java:38)
       at com.adjust.sdk.ActivityHandler$SessionHandler.handleMessage(ActivityHandler.java:353)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)
</code> </pre>

I've implemented Adjust.onResume() & Adjust.onPause() in all activities.
I'm sending INSTALL_REFERRER broadcast message thru my own BroadCastReceiver with : 
<pre><code>
public class InstallReferrerReceiver extends BroadcastReceiver {
	@Override
	public void onReceive(Context context, Intent intent) {
        // Adjust
        new com.adjust.sdk.AdjustReferrerReceiver().onReceive(context, intent);
        //....
	}
}
</pre></code>
I can't manage to reproduce this one. It seems to happen only on rooted devices.

**Comment by ajans** [comment] 2015-07-14 07:16
Hi there,

we are having the same crash with Adjust 4.0.8 with 2 older Galaxy Y devices (GT-S5369 and GT-S6102), both running on Android 2.3.6. The crash-tracking is from Crittercism.

Here is the stacktrace:

	java.lang.NullPointerException
		at com.adjust.sdk.PackageHandler.sendClickPackage(SourceFile:115)
		at com.adjust.sdk.ActivityHandler.sendReferrerInternal(SourceFile:548)
		at com.adjust.sdk.ActivityHandler.access$800(SourceFile:34)
		at com.adjust.sdk.ActivityHandler$SessionHandler.handleMessage(SourceFile:360)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loop(Looper.java:130)
		at android.os.HandlerThread.run(HandlerThread.java:60)

I have a similar setup for the install-receiver with multiple target-receivers.
How do you know this crash only seems to happen on rooted devices?

**Comment by uerceg** [comment] 2015-07-14 07:32
Hi everyone,

we are going to investigate this issue and let you know as soon as we have some updates.

@ajans Are you able to reproduce this crash? Did it happen on rooted or not rooted devices in your case?

**Comment by nonelse** [comment] 2015-07-14 13:06
Hi.
Although, it seems to be possible for v4.0.8 to run into this situation in a very limited scenario, we haven't been able to replicate it.
The good news is that, the mechanism that allows that error to occur was changed in the latest version v4.0.9. Could you try to replicate it with the new version?

Cheers.

**Comment by ajans** [comment] 2015-07-14 13:09
@uerceg I haven't been able to determine the scenario for which this crash happens. It only seem to happen at app-startup. I don't know if the affected devices are rooted or not, as Crittercism doesn't provide that information.

@nonelse I will integrate Adjust 4.0.9 with the next app-update, then we will see if the crash gets reported again.

**Comment by nonelse** [comment] 2015-10-16 12:07
It should be fixed with v4.0.9. Please open a new issue if anything happens again. Thanks

**Closed by nonelse** 2015-10-16 12:07 UTC
