### ISSUE TITLE
AdjustReferrerReceiver not working properly

### ISSUE THREAD

**Issue by Soriyyx** [adjust/android_sdk#184] opened 2016-03-30 20:21 UTC
Trackers are not working properly in our Android app. I uploaded apk with Adjust SDK installed to Google Play Beta and download it via tracker link but no install is recorded on dashboard. After a little bit of searching I've read that Android since Honeycomb doesn't allow calling broadcast receivers until an app is launched for the first time. Do you have any information on that matter? Here is the source: https://commonsware.com/blog/2011/07/13/boot-completed-regression-confirmed.html

If I call broadcast receiver from terminal with below command (I copied referrer from Google Play link tracker redirected me to)
`adb shell am broadcast -a com.android.vending.INSTALL_REFERRER -n sconnected.fancore.debug/com.adjust.sdk.AdjustReferrerReceiver --es referrer "adjust_reftag%3DcSdLBryuw9nhX%26ut`

no install is tracked in dashboard also. I however get the following log

> 03-30 22:19:38.265 11338-11338/? A/Adjust: SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing!
03-30 22:19:38.320 11338-11383/? D/Adjust: Read Attribution: tt:wgb5m6 tn:Organic net:Organic cam:null adg:null cre:null cl:null
03-30 22:19:38.325 11338-11383/? D/Adjust: Read Activity state: ec:0 sc:2 ssc:1 sl:1.7 ts:1.7 la:11:12:13 uuid:bdb68e3a-a8e9-4811-9164-5a2b7cb5f034
03-30 22:19:38.338 11338-11385/? D/Adjust: Read Package queue: []
03-30 22:19:38.338 11338-11385/? D/Adjust: Package handler read 0 packages
03-30 22:19:38.347 11338-11383/? V/Adjust: Reading query string (adjust_reftag=cSdLBryuw9nhX&utm_source=Test+Tracker) from reftag
03-30 22:19:38.362 11338-11385/? D/Adjust: Added package 1 (click)
03-30 22:19:38.363 11338-11385/? V/Adjust: Path:      /sdk_click
                                           ClientSdk: android4.6.0
                                           Parameters:
                                           	app_token        ***************
                                           	click_time       2016-03-30T22:19:38.272Z+0200
                                           	created_at       2016-03-30T22:19:38.347Z+0200
                                           	environment      sandbox
                                           	gps_adid         ******************
                                           	needs_response_details 0
                                           	referrer         adjust_reftag=cSdLBryuw9nhX&utm_source=Test+Tracker
                                           	reftag           cSdLBryuw9nhX
                                           	source           reftag
                                           	tracking_enabled 1
03-30 22:19:38.368 11338-11385/? D/Adjust: Wrote Package queue: [click]
03-30 22:19:38.369 11338-11385/? D/Adjust: Package handler wrote 1 packages
03-30 22:19:38.527 11338-11386/? V/Adjust: Response: {"app_token":"***************","adid":"***************","timestamp":"2016-03-30T20:19:38.691Z+0000","message":"Click tracked"}
03-30 22:19:38.527 11338-11386/? I/Adjust: Click tracked
03-30 22:19:38.529 11338-11385/? D/Adjust: Wrote Package queue: []
03-30 22:19:38.529 11338-11385/? D/Adjust: Package handler wrote 0 packages

Am I missing something?

Thanks, Matic

**Comment by uerceg** [comment] 2016-03-31 09:09
Hi @Soriyyx 

First of all, what I can see from your logs is that once you launched your app on the device for this test, this was not the first time that app was started on your device. Our SDK read attribution, something we call activity state and package queue:

```
03-30 22:19:38.320 11338-11383/? D/Adjust: Read Attribution: tt:wgb5m6 tn:Organic net:Organic cam:null adg:null cre:null cl:null
03-30 22:19:38.325 11338-11383/? D/Adjust: Read Activity state: ec:0 sc:2 ssc:1 sl:1.7 ts:1.7 la:11:12:13 uuid:bdb68e3a-a8e9-4811-9164-5a2b7cb5f034
03-30 22:19:38.338 11338-11385/? D/Adjust: Read Package queue: []
```

This indicates that SDK was already started before this particular launch, because all of our internal files where we are keeping track on what's going with SDK in your app have already been created and written before. So, this app launch can not trigger an install.

In order to reproduce "first app install on device" scenario, you need to do the following:

* Completely remove app from your device by uninstalling it.
* Forget your test device from our backend by following these instructions: https://docs.adjust.com/en/getting-started/#testing-attribution 
This step is important, because in this way, our backend will stop knowing your device and the next time you send session from it to us, it will be treated as an install.
* Install the app on the device and run it.

By completing these steps, you will see in the SDK verbose logs that the install has been tracked and after a while, you will see that in the `dashboard sandbox data` as well.

Second thing, your broadcast receiver triggering test in these logs looks just fine. Once triggered, our SDK sends something we call `sdk_click` which contains `reftag` information. As you can see above in the logs, that was done properly:

```
03-30 22:19:38.347 11338-11383/? V/Adjust: Reading query string (adjust_reftag=cSdLBryuw9nhX&utm_source=Test+Tracker) from reftag
03-30 22:19:38.362 11338-11385/? D/Adjust: Added package 1 (click)
03-30 22:19:38.363 11338-11385/? V/Adjust: Path: /sdk_click
ClientSdk: android4.6.0
Parameters:
app_token ***************
click_time 2016-03-30T22:19:38.272Z+0200
created_at 2016-03-30T22:19:38.347Z+0200
environment sandbox
gps_adid ******************
needs_response_details 0
referrer adjust_reftag=cSdLBryuw9nhX&utm_source=Test+Tracker
reftag cSdLBryuw9nhX
source reftag
tracking_enabled 1
```

What ever you have put as value of `adjust_reftag` parameter in `adb` command, our SDK has received and forwarded that to our backend as part of the `sdk_click` package.

If you want to simulate `INSTALL_REFERRER` intent triggering situation which happens once your app is downloaded, installed and launched once released in Play Store, I advise following scenario:

* Uninstall app from your test device.
* Forget the device from our backend like explained above.
* When running your app from Android Studio, choose that app should only be installed but not instantly launched.
* Once app is installed and still not started, run `adb` command and once hitting it, open the app.

Install should be tracked + `sdk_click` package with content of `adjust_reftag` content sent. After a while, you will see this install in dashboard sandbox traffic.

Let me know if you have any other questions.

Cheers

**Comment by uerceg** [comment] 2016-04-18 06:45
@Soriyyx Any progress with this issue?

**Comment by vanniktech** [comment] 2016-04-29 08:42
@uerceg hey there we're facing the same problem though it's a bit hard to determine what's wrong in our situation.

## Before

We had Adjust `4.2.3` running and those Proguard rules:

```
-keep class com.adjust.sdk.** { *; }
-keep class com.google.android.gms.common.** { *; }
-keep class com.google.android.gms.ads.identifier.** { *; }
```

Also we had 2 Receiver for the `INSTALL_REFERER` intent filter. One for you guys and one for Localytics.

```xml
<receiver
    android:name="com.adjust.sdk.AdjustReferrerReceiver"
    android:exported="true"
    tools:ignore="ExportedReceiver">
    <intent-filter>
        <action android:name="com.android.vending.INSTALL_REFERRER"/>
    </intent-filter>
</receiver>
<receiver
    android:name="com.localytics.android.ReferralReceiver"
    android:exported="true"
    tools:ignore="ExportedReceiver">
    <intent-filter>
        <action android:name="com.android.vending.INSTALL_REFERRER"/>
    </intent-filter>
</receiver>
```

## After

I updated the Adjust SDK to `4.6.0` and those Proguard rules:

```
-keep class com.adjust.sdk.plugin.MacAddressUtil {
    java.lang.String getMacAddress(android.content.Context);
}
-keep class com.adjust.sdk.plugin.AndroidIdUtil {
    java.lang.String getAndroidId(android.content.Context);
}
-keep class com.google.android.gms.common.ConnectionResult {
    int SUCCESS;
}
-keep class com.google.android.gms.ads.identifier.AdvertisingIdClient {
    com.google.android.gms.ads.identifier.AdvertisingIdClient$Info
        getAdvertisingIdInfo (android.content.Context);
}
-keep class com.google.android.gms.ads.identifier.AdvertisingIdClient$Info {
    java.lang.String getId ();
    boolean isLimitAdTrackingEnabled();
}
```

I also removed the two Receivers and added our custom one:

```xml
<receiver
    android:name="com.example.package.ReferrerReceiver"
    android:exported="true"
    tools:ignore="ExportedReceiver">
    <intent-filter>
        <action android:name="com.android.vending.INSTALL_REFERRER"/>
    </intent-filter>
</receiver>
```

In our custom `ReferrerReceiver` we have this code:

```java
@Override
public void onReceive(final Context context, final Intent intent) {
    final AdjustReferrerReceiver adjustReferrerReceiver = new AdjustReferrerReceiver();
    adjustReferrerReceiver.onReceive(context, intent);

    final ReferralReceiver localyticsReferralReceiver = new ReferralReceiver();
    localyticsReferralReceiver.onReceive(context, intent);
}
```

Now we tried testing it and we got 5 clicks but only 1 install so far, which seems odd. Is there a delay involved with the installs?

Also I tried forgetting two devices (One Android 6, One is N Preview), with one it did work with the other one it did not. On both phones I uninstalled the app and then clicked on the link with the ad. After that I installed the app in the Play Store, opened it. That should be enough, right?

To forget the device I opened those urls in the browser:

```
https://app.adjust.com/forget_device?app_token=<app_token>&android_id=<android_id>
https://app.adjust.com/forget_device?app_token=<app_token>&android_id=<ad_id>
https://app.adjust.com/forget_device?app_token=<app_token>&gps_adid=<android_id>
https://app.adjust.com/forget_device?app_token=<app_token>&gps_adid=<ad_id>
```

On three of those I got `Device not found` and on one I got `Forgot device`. Though even on that one request where I got `Forget device`, I never got something like that (taken from [here](https://docs.adjust.com/en/getting-started/#testing-attribution)):

```
tracker: f0ob4r
event pingback: < optionally an associated event callback >
```

I mentioned that we tried it on 5 devices, on the other 3 phones the app itself was never installed. So the server could under no circumstance know about the device and hence it should work out of the box.

**NOTE:** Are you guys aware that the MAC Address is always the same starting with Android 6?

**Comment by uerceg** [comment] 2016-05-09 10:25
@vanniktech Please, sorry for delayed answer.

Can you explain me a bit this part:
```
Now we tried testing it and we got 5 clicks but only 1 install so far, which seems odd. Is there a delay involved with the installs?
```
Can you explain me how did you make 5 clicks, was it from same device?

As far as custom broadcast receiver implementation and forgetting the device scenario are concerned - everything looks fine. If you see `Forgot device`, that's perfectly fine, it indicates that our backend forgot your test device and that if you uninstalled the app from it, next time you install it and run it with our SDK inside, that launch will be tracked as an install.

**Comment by vanniktech** [comment] 2016-05-09 10:32
Don't worry it actually does work now. It just took some time in Adjust to receive the installed (some took couple of hours, some more than a day). However the click events were almost instant. We had one issue in earlier testing though.

Assume that the package name is `com.example`. Our custom `ReferralReceiver` was declared in the manifest as:

```xml
<receiver android:name=".CustomReceiver"
```

This variant does not work so we had to declare it with stating the package name

```xml
<receiver android:name="com.example.CustomReceiver"
```

After that everything worked. Also we now have Adjust 4.6.0 with the Proguard rules from above which are the same as the README here. Haven't upgraded to 4.7.0 though. Are there any concerns or can we just upgrade minor versions since they are backwards compatible?

**Comment by uerceg** [comment] 2016-05-09 10:42
Ah, okay, we actually weren't checking the `.CustomReceiver` scenario, we are actually advising in our docs to use it like you did in 2nd scenario, so with `com.example` in front: https://github.com/adjust/android_sdk/blob/master/doc/referrer.md

In theory, all our minor versions are backwards compatible. With each new minor version, we are trying to introduce some new features in our SDK and to improve stability of SDK in general. So, if you are fine with SDK `v4.6.0` and features it offers to you, you can as well stick with that version and use it.

Our general rule of thumb is always to advise people to always keep our SDK in their apps up to date, but that's no obligatory thing, of course.

**Comment by uerceg** [comment] 2016-05-09 10:57
Great, glad it worked. 👍 

@Soriyyx Feel free to reopen this issue if you still face it.

Cheers

**Closed by uerceg** 2016-05-09 10:57 UTC
